---
title: "Akimova et al (in prep)"
description:
date: 2022-10-05
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
preview: THUENEN_PRINT_CMYK.jpg
---

# Akimova et al (in prep) 

## Summary

This model has been applied to explore feeding and growth of herring larvae during the first month of their live in the North Sea. Two spawning components were compared: Buckan/Banks areas in autumn and Downs area in winter. Prey fields were obtained from field samples.  Larvae between 5 and 26 mm length were simulated to match with the length range of observed herring larvae. The model was largely based on the physiological model parameterized for herring larvae by Hufnagl and Peck (2011). Three modifications to the original model were applied:

1) a new parameterization of the standard respiration rate $R_s$ was based on the recent measurements made by  Moyano et al.(2018):
$$
R_s = 0.02\;⋅W_{l}^{0.886}\;⋅exp(0.105⋅T)
$$
 where $W_{l}$ is larval dry weight [mg] and $T$ is temperature
 
2) a Boolean function was used for the dynamic energy allocation paremeter $p$ following Huebert and Peck (2014):
$$
(p=1,\;if \; \;W_l>W_{ref}) \; \;and \; \; (p=0, \; \;if \; \;W_l≤W_{ref})
$$
where $W_{ref}$ is the reference larval weight

3) activity multiplicator k was k=2 during the daytime and k=1 during the night following Huebert and Peck (2014):


## Relations

1) Hufnagl and Peck (2011)
2) Quirks model ( Huebert and Peck (2014))


### R Code

### Matlab Code


### Matlab Code
<div class="contributor_org">
`r xfun::embed_file(here::here("_herring", "Anna Akimovas Model", "main_simulation.m"), text = "main_simulation.m")`
</div>

<div class="contributor_org">
`r xfun::embed_file(here::here("_herring", "Anna Akimovas Model", "energy_budget.m"), text = "energy_budget.m")`
</div>


<div class="contributor_org">
`r xfun::embed_file(here::here("_herring", "Anna Akimovas Model", "energy_allocation_and_growth.m"), text = "energy_allocation_and_growth.m")`
</div>

<div class="contributor_org">
`r xfun::embed_file(here::here("_herring", "Anna Akimovas Model", "optimal_foraging.m"), text = "optimal_foraging.m")`
</div>

<div class="contributor_org">
`r xfun::embed_file(here::here("_herring", "Anna Akimovas Model", "size_spectrum_zooplankton (2).m"), text = "size_spectrum_zooplankton (2).m")`
</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(astsa)
#https://donsteward.blogspot.com/search/label/boxplots
```


### Fortran Code
i=1
...

## Publications

## Equations

## Known Mistakes

1) Corrected equation for the assimilation efficiency: 
$$
β=0.6⋅(1-0.3⋅\;exp(c))
$$
where $$ c=-0.003.(W_l-W_{min}) $$
2) Corrected and simplified equation for the maximal gut content $GCmax$: 
$$GCmax=0.045⋅(W_{ref})^{1.02}$$

# Contact Authors
anna.akimova@thuenen.de